### ISSUE TITLE
Error "TypeError: callback is not a function"

### ISSUE THREAD

**Issue by andretunes** [apocas/node-whmcs#31]
Good afternoon,
My name is André, I'm from Portugal and I'm getting this error:
`/home/container/node_modules/whmcs/lib/utils.js:50
return callback(new Error('WHMCS Error (' + statusCode + '): ' + data.message));
^
TypeError: callback is not a function
at send (/home/container/node_modules/whmcs/lib/utils.js:50:16)
at Request._callback (/home/container/node_modules/whmcs/lib/utils.js:79:9)
at Request.self.callback (/home/container/node_modules/request/index.js:148:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/home/container/node_modules/request/index.js:876:14)
at Request.emit (events.js:203:15)
at IncomingMessage.<anonymous> (/home/container/node_modules/request/index.js:827:12)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)`

I referenced the line above. Hope you can help me and congrats for you work.

Kind regards!

https://github.com/apocas/node-whmcs/blob/e162a6253627bf852ae88a9ba987990bdb140bda/lib/utils.js#L50

**Comment by apocas** [comment]
Did you supplied a callback? 
It seems you are missing a callback in one of your calls.

Callback isn't type checked unfortunately (tomorrow I will patch this)

**Comment by andretunes** [comment]
Hello,
Yes i copied the example.

Thank you for the help.

Pedro Dias <notifications@github.com> escreveu no dia terça, 31/03/2020
à(s) 04:29:

**Comment by andretunes** [comment]
Hello,
Any news?

**Comment by apocas** [comment]
Where is the example code?
You copied the exception. A callback is missing for sure.

I will type check the callback, but for now just always use a callback.

**Comment by andretunes** [comment]
Hello,
Can you give me an examplo to get for example the name of a client inside a ticket?

Kind regards!
